# Generated by Django 5.1.7 on 2025-03-24 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="type",
            field=models.CharField(
                choices=[
                    ("admin", "admin"),
                    ("suplier", "suplier"),
                    ("client", "client"),
                ],
                default="client",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="SuplierRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("resoan", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_statement",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="suplier_request/account_statement",
                    ),
                ),
                (
                    "commercial_register",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="suplier_request/commercial_register",
                    ),
                ),
                (
                    "tax_card",
                    models.FileField(
                        blank=True, null=True, upload_to="suplier_request/tax_card"
                    ),
                ),
                (
                    "id_card",
                    models.FileField(
                        blank=True, null=True, upload_to="suplier_request/id_card"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
