# Generated by Django 5.1.7 on 2025-03-24 05:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="ProductImage",
        ),
    ]
