# Generated by Django 5.1.7 on 2025-03-24 20:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_ar",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ar",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="label_ar",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="label_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_ar",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="review_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="review_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_ar",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
