# Generated by Django 5.1.7 on 2025-03-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_coupon_product_slug_card_order_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
