# Generated by Django 5.1.7 on 2025-03-27 09:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="description_ar",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="about",
            name="job_title_ar",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="about",
            name="name_ar",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mission",
            name="description_ar",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vission",
            name="description_ar",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
