# Generated by Django 5.1.7 on 2025-03-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_about_description_ar_about_job_title_ar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="image",
            field=models.FileField(upload_to="about/"),
        ),
    ]
