# Generated by Django 5.1.7 on 2025-03-27 10:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_about_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="refund_and_policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", ckeditor.fields.RichTextField()),
                ("description_ar", ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name="Terms_and_condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", ckeditor.fields.RichTextField()),
                ("description_ar", ckeditor.fields.RichTextField()),
            ],
        ),
    ]
